### ISSUE TITLE
Question about filtering

### ISSUE THREAD

**Issue by James94665** [rickoooooo/RDPwnFinder#1]
Hey there, Have to say that this tool is awesome!

I was wondering if it was possible to make the AI detect pics that require passwords to access cmd.exe or dwm.exe and sort them as clean or password protected?

**Comment by rickoooooo** [comment]
The training model that comes with the repo only supports the current
"clean" versus "hacked" definitions. But if you download your own training
data (meaning that you screenshot several thousand RDP servers) you can
sort them however you want and then train a new model. You would just put
those password protected backdoored images into the "clean" directory along
with all the other clean stuff and then train a new model.
