### ISSUE TITLE
make or add in code to check lwin+u

### ISSUE THREAD

**Issue by bobwish** [rickoooooo/RDPwnFinder#4]
this only check sethc.exe or 5xshift. can you add,update or something to check utilman.exe = lwin key + U .

**Comment by rickoooooo** [comment]
That is on the roadmap, but I'm not sure when I'll be able to get around to it.

**Comment by rickoooooo** [comment]
I should add that this would require the collection of more training images and then training a new model for the classifier.

**Comment by bobwish** [comment]
if you can add this change it would be awesome, i dont care for training. i have try some combinations but wont work not sure why. or send me here what changes has to be done.. thanks
